name: flutter_oauth
description: A flutter oauth package for performing oauth operations
version: 1.0.0
author: Hitherejoe, Kevin A. Riedl <k.riedl@codeing.io>
homepage: https://codeing.io

environment:
  sdk: ">=2.1.0-dev.9.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0
  flutter_webview_plugin: ^0.3.0+2


flutter:
